config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  get "/forecast/:id", to: "addresses#forecast", as: 'forecast'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "addresses#index"
end

app/models/address.rb
class Address < ApplicationRecord
    validates :street, presence: true
    validates :city, presence: true
    validates :zip, presence: true

    def to_s()
        "#{street}, #{city}, #{zip}"
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  require "faraday"
  require 'uri'
  before_action :set_address, only: %i[ show edit update destroy forecast]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
    @location = fetch_location(@address)
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # GET /addresses/1/forecast
  def forecast
    @location = fetch_location(@address)
    @forecast = fetch_forcast(@location)
  end
  
  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)
    @location = fetch_location(@address)
    # binding.break
    respond_to do |format|
      if @location && @address.save
        format.html { redirect_to address_url(@address), notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy!

    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:street, :city, :state, :zip)
    end

    # fetch the geocoded location for given address.
    def fetch_location(address)
      geolocation_url = "https://geocoding.geo.census.gov/geocoder/locations/address" # ?street=#{street}&city=#{city}&state=#{address.state}&zip=#{address.zip}&benchmark=Public_AR_Current&format=json"
      params =  {street: URI.encode_uri_component(address.street), 
        city: URI.encode_uri_component(address.city), 
        state:URI.encode_uri_component(address.state), 
        zip: URI.encode_uri_component(address.zip),
        benchmark: "Public_AR_Current",
        format: "json"
      }
      response = faraday_conn.get(geolocation_url, params)
      if response.status == 200 
        match = response.body["result"]["addressMatches"].first
        lat = match["coordinates"]["x"]
        long = match["coordinates"]["y"]
        mached_addr = match["matchedAddress"]
        location = {lat: lat, long: long, mached_addr: mached_addr}
      else
        location = nil
      end
      location
    end

    # fetch forecast for location from National weather service API.
    def fetch_forcast(location)
      lat = sprintf("%0.04f", location[:lat])
      long = sprintf("%0.04f", location[:long])
      weather_url = "https://api.weather.gov/points/#{long},#{lat}" 
      response = get_with_cache(weather_url)

      if response.status == 200 
        forcast_url = response.body["properties"]["forecast"]
        hourly_forcast_url = response.body["properties"]["forecastHourly"]
      else
        "Error fectching Forcast"
      end

      response = get_with_cache(forcast_url)
      response.body["properties"]["periods"]
    end

    def get_with_cache(path, expires_in: 30.minutes)
      # Compute a cache key that is unique for the API, path
      request_fingerprint = Digest::SHA256.hexdigest({ path: }.inspect)
      key = "points/#{request_fingerprint}"
    
      Rails.cache.fetch(key, expires_in:) do
        faraday_conn.get(path)
      end
    end

    # create a Faraday connection.
    def faraday_conn() 
      @faraday ||= begin
        options = {
          request: {
            open_timeout: 1,
            read_timeout: 1,
            write_timeout: 1
          }
        }
        conn = Faraday.new(**options) do |config|
          config.response :json
          config.response :raise_error
          config.response :logger, Rails.logger, headers: true, bodies: true, log_level: :debug 
          config.adapter :net_http
        end
      end
  
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Street:</strong>
    <%= address.street %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">City:</strong>
    <%= address.city %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">State:</strong>
    <%= address.state %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Zip:</strong>
    <%= address.zip %>
  </p>

  <% if loc.nil? %>
    <p class="my-5">
    <strong class="block font-medium mb-1">Location not found! </strong>
    </p>
  <% else %>
    <p class="my-5">
      <strong class="block font-medium mb-1">Lat: </strong>
      <%= loc[:lat] %> 
      <strong class="block font-medium mb-1">Long: </strong>
      <%= loc[:long] %> 
    </p>
  <% end %>

  <% if action_name != "show" %>
    <%= link_to "Forecast", forecast_path(address), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Show", address, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Destroy", address_path(address), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/addresses/_form.html.erb
<%= form_with(model: address, class: "contents") do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :street %>
    <%= form.text_field :street, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :city %>
    <%= form.text_field :city, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :state %>
    <%= form.text_field :state, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :zip %>
    <%= form.text_field :zip, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing address</h1>

  <%= render "form", address: @address %>

  <%= link_to "Show this address", @address, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to addresses", addresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/addresses/forecast.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <p class="my-5">
    <strong class="block font-medium mb-1">Matched address: </strong>
    <%=  @location[:mached_addr] %> 
    </p>
    <h2> <%= @forecast[0]["name"] %>
    <ul>
        <li> Temperature: <%= "#{@forecast[0]["temperature"]} #{@forecast[0]["temperatureUnit"]}" %> </li>
        <li> Humidity:    <%= @forecast[0]["relativeHumidity"]["value"] %>%</li>
        <li> Wind Speed: <%= @forecast[0]["windSpeed"] %></li>
        <li> Wind Direction: <%= @forecast[0]["windDirection"] %></li>
        <li> Forecast: <%= @forecast[0]["shortForecast"] %></li>
    </ul>

    <p class="my-5">
    <strong class="block font-medium mb-1">Detailed Forecast: </strong>
    <%=  @forecast[0]["detailedForecast"] %> 
    </p>
    <hr>
    <% (2..12).each do |day| %>
    <h2> <%= @forecast[day]["name"] %>
    <ul>
        <li> Temperature: <%= "#{@forecast[day]["temperature"]} #{@forecast[day]["temperatureUnit"]}" %> </li>
        <li> Forecast: <%= @forecast[day]["shortForecast"] %></li>
        <hr>
    </ul>
    <% end %>

    <%= link_to "Back to addresses", addresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/addresses/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Addresses</h1>
    <%= link_to "New address", new_address_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="addresses" class="min-w-full">
    <%= render @addresses, loc: @location %>
  </div>
</div>

app/views/addresses/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New address</h1>

  <%= render "form", address: @address %>

  <%= link_to "Back to addresses", addresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/addresses/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @address, loc: @location %>

    <%= link_to "Forecast", forecast_path(@address), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit", edit_address_path(@address), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Destroy", address_path(@address), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    <%= link_to "Back", addresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>